// login-vue/src/components/Sidebar.vue
<template>
  <aside class="sidebar" :class="{ collapsed }">
    <div class="sidebar-header">
      <div class="logo">
        <div class="logo-icon">
          <el-icon><TrendCharts /></el-icon>
        </div>
        <transition name="fade">
          <span v-if="!collapsed" class="logo-text">管理系统</span>
        </transition>
      </div>
    </div>

    <nav class="sidebar-nav">
      <el-menu
        :default-active="activeMenu"
        :collapse="collapsed"
        :collapse-transition="false"
        background-color="transparent"
        text-color="#333"
        active-text-color="#dc2626"
      >
        <el-menu-item index="/home" @click="navigate('/home')">
          <el-icon><HomeFilled /></el-icon>
          <template #title>首页</template>
        </el-menu-item>

        <el-menu-item index="/profile" @click="navigate('/profile')">
          <el-icon><User /></el-icon>
          <template #title>个人资料</template>
        </el-menu-item>

        <el-sub-menu index="system">
          <template #title>
            <el-icon><Setting /></el-icon>
            <span>系统管理</span>
          </template>
          <el-menu-item index="/system/users" @click="navigate('/system/users')">
            <el-icon><User /></el-icon>
            <template #title>用户管理</template>
          </el-menu-item>
        </el-sub-menu>
      </el-menu>
    </nav>

    <div class="sidebar-footer">
      <el-button
        class="logout-btn"
        :icon="SwitchButton"
        @click="handleLogout"
        :circle="collapsed"
      >
        <span v-if="!collapsed">退出登录</span>
      </el-button>
    </div>
  </aside>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import {
  TrendCharts,
  HomeFilled,
  User,
  DataAnalysis,
  Setting,
  SwitchButton
} from '@element-plus/icons-vue'

const props = defineProps({
  collapsed: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['toggle'])

const router = useRouter()
const route = useRoute()

const activeMenu = computed(() => route.path)

const navigate = (path) => {
  if (path === route.path) return

  router.push(path)
}

const handleLogout = () => {
  localStorage.removeItem('token')
  localStorage.removeItem('userInfo')
  ElMessage.success('已退出登录')
  router.push('/login')
}
</script>

<style scoped>
.sidebar {
  position: fixed;
  left: 0;
  top: 0;
  bottom: 0;
  width: 280px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.95), rgba(255, 255, 255, 0.9));
  backdrop-filter: blur(20px);
  border-right: 1px solid rgba(255, 255, 255, 0.8);
  box-shadow: 4px 0 20px rgba(220, 38, 38, 0.08);
  display: flex;
  flex-direction: column;
  z-index: 200;
  transition: width 0.3s ease;
}

.sidebar.collapsed {
  width: 80px;
}

.sidebar-header {
  height: 70px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-bottom: 1px solid rgba(220, 38, 38, 0.1);
  padding: 0 20px;
}

.logo {
  display: flex;
  align-items: center;
  gap: 12px;
}

.logo-icon {
  width: 40px;
  height: 40px;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-size: 24px;
  flex-shrink: 0;
}

.logo-text {
  font-size: 20px;
  font-weight: 700;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  white-space: nowrap;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.sidebar-nav {
  flex: 1;
  padding: 20px 0;
  overflow-y: auto;
}

.sidebar-nav::-webkit-scrollbar {
  width: 4px;
}

.sidebar-nav::-webkit-scrollbar-thumb {
  background: rgba(220, 38, 38, 0.3);
  border-radius: 2px;
}

:deep(.el-menu) {
  border: none;
}

:deep(.el-menu-item) {
  margin: 4px 12px;
  border-radius: 12px;
  transition: all 0.3s ease;
}

:deep(.el-menu-item:hover) {
  background: rgba(220, 38, 38, 0.08) !important;
}

:deep(.el-menu-item.is-active) {
  background: linear-gradient(135deg, rgba(220, 38, 38, 0.15), rgba(245, 158, 11, 0.15)) !important;
  color: var(--color-primary) !important;
}

/* 子菜单样式统一 */
:deep(.el-sub-menu) {
  margin: 4px 12px;
}

:deep(.el-sub-menu__title) {
  border-radius: 12px;
  transition: all 0.3s ease;
  margin: 0;
}

:deep(.el-sub-menu__title:hover) {
  background: rgba(220, 38, 38, 0.08) !important;
}

:deep(.el-sub-menu.is-active .el-sub-menu__title) {
  background: linear-gradient(135deg, rgba(220, 38, 38, 0.15), rgba(245, 158, 11, 0.15)) !important;
  color: var(--color-primary) !important;
}

/* 二级菜单项样式 */
:deep(.el-sub-menu .el-menu-item) {
  margin: 4px 12px 4px 24px;
  min-width: auto;
}

.sidebar-footer {
  padding: 20px;
  border-top: 1px solid rgba(220, 38, 38, 0.1);
}

.logout-btn {
  width: 100%;
  background: rgba(220, 38, 38, 0.1);
  border: none;
  color: var(--color-primary);
  font-weight: 500;
}

.logout-btn:hover {
  background: rgba(220, 38, 38, 0.2);
}

.sidebar.collapsed .logout-btn {
  width: 40px;
  height: 40px;
}

@media (max-width: 768px) {
  .sidebar {
    transform: translateX(-100%);
  }

  .sidebar.collapsed {
    transform: translateX(0);
    width: 80px;
  }
}
</style>

// login-react/src/components/Sidebar.tsx
import React from 'react'
import { Menu } from 'antd'
import {
  HomeOutlined,
  UserOutlined,
  TeamOutlined,
  SettingOutlined,
  FolderOutlined,
  SafetyOutlined
} from '@ant-design/icons'
import { useNavigate, useLocation } from 'react-router-dom'
import type { MenuProps } from 'antd'

interface SidebarProps {
  collapsed: boolean
  onToggle: () => void
}

const Sidebar: React.FC<SidebarProps> = ({ collapsed, onToggle }) => {
  const navigate = useNavigate()
  const location = useLocation()

  const handleMenuClick = ({ key }: { key: string }) => {
    navigate(`/${key}`)
  }

  const items: MenuProps['items'] = [
    {
      key: 'home',
      icon: <HomeOutlined />,
      label: '首页'
    },
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: '个人资料'
    },
    {
      key: 'system',
      icon: <SettingOutlined />,
      label: '系统管理',
      children: [
        {
          key: 'system/users',
          icon: <TeamOutlined />,
          label: '用户管理'
        },
        {
          key: 'system/roles',
          icon: <SafetyOutlined />,
          label: '角色管理'
        },
        {
          key: 'system/positions',
          icon: <FolderOutlined />,
          label: '岗位管理'
        }
      ]
    }
  ]

  const getSelectedKeys = (): string[] => {
    const path = location.pathname
    if (path === '/home') return ['home']
    if (path === '/profile') return ['profile']
    if (path.includes('/system/users')) return ['system/users']
    if (path.includes('/system/roles')) return ['system/roles']
    if (path.includes('/system/positions')) return ['system/positions']
    return []
  }

  return (
    <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}>
      <div className="sidebar-header">
        <div className="logo">
          <span className="logo-icon">A</span>
          {!collapsed && <span className="logo-text">AdminHub</span>}
        </div>
      </div>

      <Menu
        mode="inline"
        theme="light"
        selectedKeys={getSelectedKeys()}
        items={items}
        inlineCollapsed={collapsed}
        onClick={handleMenuClick}
        className="sidebar-menu"
      />
    </aside>

  <style>{`
    .sidebar {
      position: fixed;
      top: 0;
      left: 0;
      width: 280px;
      height: 100vh;
      background: linear-gradient(135deg,
        rgba(255, 255, 255, 0.95) 0%,
        rgba(255, 255, 255, 0.7) 100%);
      transition: all 0.3s ease;
      z-index: 100;
    }

    .sidebar-header {
      display: flex;
      align-items: center;
      padding: 0 40px 0 20px;
    }

    .logo {
      display: flex;
      align-items: center;
      gap: 1rem;
    }

    .logo-icon {
      width: 40ra;
      height: 40ra;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      background: linear-gradient(135deg, var(--color-primary) 0%, var(--color-accent) 100%);
      color: white;
      font-size: 1.75rem;
    }

    .logo-text {
      font-family: var(--font-display);
      font-size: 1.25rem;
      font-weight: 700;
      color: var(--color-text);
      transition: all 0.3s ease;
    }

    .sidebar-menu {
      border: none;
    }

    @media (max-width: 768px) {
      .sidebar {
        display: none;
      }

      .sidebar-header {
        padding: 0 24px 0;
      }
    }
  `}</style>
  )
}

export default Sidebar
